### ISSUE TITLE
Repository instructions

### ISSUE THREAD

**Issue by sebschneid** [wirvsvirus-dortmund/backend#7]
### 1. Get poetry

`python install poetry` didn't work, error "_can't open file 'install': [Errno 2] No such file or directory_".

Used `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python` from the [poetry install instructions](https://python-poetry.org/docs/) instead.

### 4. Run database migrations
Error _KeyError: 'DATABASE_URI'_ at ` SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URI']`

Variable should probably set in `env-template`. Worked with `export DATABASE_URI=sqlite:////tmp/test.db`

**Comment by maxnoe** [comment]
pip install poetry ;)

**Comment by maxnoe** [comment]
Fixed master, sorry
